stages:
  - build
  - test
  - review
  - stage
  - production

build:
  stage: build
  script:
    - echo 'Building'

test unit:
  stage: test
  script:
    - echo 'Unit Testing 1'

test integration:
  stage: test
  script:
    - echo 'Integration Testing 2'

dev:
  stage: review
  script:
    - echo 'Deploy to Dev'
  environment:
    name: dev
    url: http://dev.example.com # define GitLab CI to use external URL for this job

branch review:
  stage: review
  script:
    - echo "Deploy to $CI_ENVIRONMENT_SLUG"
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master

stage:
  stage: stage
  when: manual # run job only manual from ui of GitLab CI
  only:
    - /^\d+\.\d+.\d+/ # filter the commits match the pattern of tags (example: tag: 2.4.10)
  script:
    - echo 'Deploy to Stage'
  environment:
    name: stage
    url: https://beta.example.com # define GitLab CI to use external URL for this job

production:
  stage: production
  when: manual # run job only manual from ui of GitLab CI
  only:
    - /^\d+\.\d+.\d+/ # filter the commits match the pattern of tags (example: tag: 2.4.10)
  script:
    - echo 'Deploy to Production'
  environment:
    name: production
    url: https://example.com # define GitLab CI to use external URL for this job

