stages:
  - build
  - test
  - review

build_job:
  stage: build
  script:
    - echo 'Building'

test_unit_job:
  stage: test
  script:
    - echo 'Unit Testing 1'

test_integration_job:
  stage: test
  script:
    - echo 'Integration Testing 2'

deploy_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://104.199.11.69

